package blazing.https;

/**
 *
 * @author hexaredecimal
 */

public enum MimeType {
	THREE_DM("x-world/x-3dmf"),
	THREE_DMF("x-world/x-3dmf"),
	SEVEN_Z("application/x-7z-compressed"),
	A("application/octet-stream"),
	AAB("application/x-authorware-bin"),
	AAM("application/x-authorware-map"),
	AAS("application/x-authorware-seg"),
	ABC("text/vnd.abc"),
	ACGI("text/html"),
	AFL("video/animaflex"),
	AI("application/postscript"),
	AIF("audio/aiff"),
	AIFC("audio/aiff"),
	AIFF("audio/aiff"),
	AIM("application/x-aim"),
	AIP("text/x-audiosoft-intra"),
	ANI("application/x-navi-animation"),
	AOS("application/x-nokia-9000-communicator-add-on-software"),
	APS("application/mime"),
	ARC("application/octet-stream"),
	ARJ("application/arj"),
	ART("image/x-jg"),
	ASF("video/x-ms-asf"),
	ASM("text/x-asm"),
	ASP("text/asp"),
	ASX("application/x-mplayer2"),
	AU("audio/basic"),
	AVI("video/avi"),
	AVS("video/avs-video"),
	BCPIO("application/x-bcpio"),
	BIN("application/octet-stream"),
	BM("image/bmp"),
	BMP("image/bmp"),
	BOO("application/book"),
	BOOK("application/book"),
	BOZ("application/x-bzip2"),
	BSH("application/x-bsh"),
	BZ("application/x-bzip"),
	BZ2("application/x-bzip2"),
	C("text/plain"),
	C_PLUS_PLUS("text/plain"),
	CAT("application/vnd.ms-pki.seccat"),
	CC("text/x-c"),
	CCAD("application/clariscad"),
	CCO("application/x-cocoa"),
	CDF("application/cdf"),
	CER("application/pkix-cert"),
	CHA("application/x-chat"),
	CHAT("application/x-chat"),
	CLASS("application/java"),
	COM("application/octet-stream"),
	CONF("text/plain"),
	CPIO("application/x-cpio"),
	CPP("text/x-c"),
	CPT("application/mac-compactpro"),
	CRL("application/pkcs-crl"),
	CRT("application/pkix-cert"),
	CSH("application/x-csh"),
	CSS("text/css"),
	CSV("text/csv"),
	CXX("text/plain"),
	DCR("application/x-director"),
	DOC("application/msword"),
	DOCX("application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
	DOT("application/msword"),
	DV("video/x-dv"),
	DVI("application/x-dvi"),
	DXF("application/dxf"),
	EPS("application/postscript"),
	EXE("application/octet-stream"),
	GIF("image/gif"),
	GZ("application/x-gzip"),
	H("text/plain"),
	HTM("text/html"),
	HTML("text/html"),
	ICO("image/x-icon"),
	JAVA("text/x-java-source"),
	JPEG("image/jpeg"),
	JPG("image/jpeg"),
	JS("application/javascript"),
	JSON("application/json"),
	MID("audio/midi"),
	MIDI("audio/midi"),
	MKV("video/x-matroska"),
	MOV("video/quicktime"),
	MP3("audio/mpeg"),
	MP4("video/mp4"),
	MPEG("video/mpeg"),
	MPG("video/mpeg"),
	OGG("audio/ogg"),
	PDF("application/pdf"),
	PNG("image/png"),
	PPT("application/vnd.ms-powerpoint"),
	PPTX("application/vnd.openxmlformats-officedocument.presentationml.presentation"),
	RTF("application/rtf"),
	SVG("image/svg+xml"),
	TAR("application/x-tar"),
	TXT("text/plain"),
	WAV("audio/wav"),
	WEBM("video/webm"),
	WMA("audio/x-ms-wma"),
	WMV("video/x-ms-wmv"),
	XLS("application/vnd.ms-excel"),
	XLSX("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
	XML("application/xml"),
	ZIP("application/zip");

	private final String mimeType;

	MimeType(String mimeType) {
		this.mimeType = mimeType;
	}

	public String getMimeType() {
		return mimeType;
	}
}
